version: "3.8"

services:
  oracle-xe:
    image: gvenzl/oracle-xe:latest
    networks:
      - bd2-network
    environment:
      ORACLE_RANDOM_PASSWORD: true
      APP_USER: oracle_user
      APP_USER_PASSWORD: oracle_password
    ports:
      - "1521:1521"

networks:
  bd2-network:
