version: "3.8"

services:
  oracle-xe:
    image: gvenzl/oracle-xe:latest
    container_name: bd2-oracle
    networks:
      - bd2-network
    env_file: .env
    ports:
      - "1521:1521"

networks:
  bd2-network:
